# Generated by Django 4.2.30 on 2026-09-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0124_agent_pipeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pinned_workspace_id",
            field=models.UUIDField(null=True),
        ),
    ]
